apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-services
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-services
  template:
    metadata:
      labels:
        app: user-services
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: user-services
        image: adhithia21/golangapp:14 # {"$imagepolicy": "flux-system:user-services"}
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 8000
